server:
    port: 11009
    
spring:
    application:
        name: blog-websocket
    #profiles: dev
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://134.175.91.16:3306/blogChat?characterEncoding=utf-8
        username: root
        password: h123456
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
    jpa:
        database: MySQL
        show‐sql: true
        generate‐ddl: true
    redis:
        host: 134.175.91.16
    data:
        mongodb:
            #host: 134.175.91.16
            #database: spitdb
            #username: root
            #password: 123456
            #port: 27017
            uri: mongodb://134.175.91.16:27017/chatdb