server:
    port: 11009
    
spring:
    application:
        name: blog-websocket

thymeleaf:
    prefix: /templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    content-type: text/html