server:
    port: 9008
spring:
    application:
        name: tenthpower-sms #指定服务名
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://134.175.91.16:3306/tensquare_sms?characterEncoding=utf-8
        username: root
        password: h123456
    jpa:
        database: MySQL
        show‐sql: true
        generate‐ddl: true
    security: #参考资料https://blog.csdn.net/rickiyeat/article/details/72639596
        basic:
            enabled: true
            path: /swagger-ui.html
        user:
            name: admin
            password: admin
    profiles:
        # active: dev,no-liquibase # 未配置dev的配置文件
        include: swagger